### ISSUE TITLE
[Bug]: In version 0.5.0, isQA() is called in the bindService() method, but the version limit of API33 is not added, resulting in a crash.

### ISSUE THREAD

**Issue by gxd523** [MetaMask/metamask-android-sdk#100]
### Provide environment information

Please release a new version as soon as possible to fix this problem. I noticed that you have submitted a fix for this problem.

### MetaMask Android SDK Version

0.5.0

### MetaMask Mobile app Version

7.12.0

### Android Version

32

### Describe the Bug

In version 0.5.0, isQA() is called in the bindService() method, but the version limit of API33 is not added, resulting in a crash.

### Expected Behavior

.

### To Reproduce

.

**Comment by philos3** [comment]
any update

**Comment by christopherferreira9** [comment]
Hi all! Version `0.5.1` has been released today.
