### ISSUE TITLE
Adding a new chain Network manually

### ISSUE THREAD

**Issue by Rathore2696** [MetaMask/metamask-android-sdk#128]
# Help Needed

 How to add any network manually apart from the list of predefined networks provided in Metamask mobile application using MetaMask SDK from an Android application ?

## Why it is needed

 I am trying to add  testnet manually

**Comment by elefantel** [comment]
Hi @Rathore2696 you can add it using [wallet_addethereumchain](https://docs.metamask.io/wallet/reference/wallet_addethereumchain). You'll need to specify the rpcUrl for your testnet as shown in the documentation. Note all the fields that are required.
