### ISSUE TITLE
use ethereum.connect start MetaMaskAPP Unable to connect

### ISSUE THREAD

**Issue by RPeast** [MetaMask/metamask-android-sdk#133]
use ethereum.connect() Will automatically evoke MetaMaskApp , But I couldn't keep my app connected to MetaMaskApp， I need to manually go back to my app and call ethereum.connect() again .
This will lead to an extra step of action, whether it can be optimized

**Comment by elefantel** [comment]
Hi @RPeast thanks for reporting the issue. Can you please record a video of the issue so that we can understand it better?

**Comment by RPeast** [comment]
> Hi @RPeast thanks for reporting the issue. Can you please record a video of the issue so that we can understand it better?

I use enableDebug(false) and Start the metamask App manually before connect() ，Solved the problem
