### ISSUE TITLE
Failed to resolve: MetaMaskAndroidSDKClient:ecies:unspecified 

### ISSUE THREAD

**Issue by hamidrazacybotics** [MetaMask/metamask-android-sdk#26]
Failed to resolve: MetaMaskAndroidSDKClient:ecies:unspecified 

this is not downloading not able to compile project

after adding 
 implementation 'io.metamask.androidsdk:metamask-android-sdk:0.1.0'

**Comment by elefantel** [comment]
I will close this issue as it has been resolved, please feel free to open a new one if you still experience it.
