### ISSUE TITLE
Introducing the sdk generated two desktop icons

### ISSUE THREAD

**Issue by xionglihui** [MetaMask/metamask-android-sdk#30]
implementation 'io.metamask.androidsdk:metamask-android-sdk:0.1.2'

Can be deleted metamask-android-sdk  android.intent.category.LAUNCHE?

**Comment by elefantel** [comment]
Hi @xionglihui , are you referring to the icons for the example app? They are not part of the SDK but app icons for the example app. 

They should not be part of the SDK if you add the SDK via `'io.metamask.androidsdk:metamask-android-sdk:0.1.2'` but only when you clone the Github repo. Are you getting it when integrating the SDK this way? In which path is it located?

**Comment by dearestwilson** [comment]
引入SDK后，桌面生成两个LAUNCHER 图标。。。。

**Comment by dearestwilson** [comment]
<activity
            android:name="io.metamask.androidsdk.MainActivity"
            android:exported="true"
            >
            <intent-filter tools:node="removeAll">
            </intent-filter>
        </activity>

**Comment by dearestwilson** [comment]
![1695009597042](https://github.com/MetaMask/metamask-android-sdk/assets/10183369/89caab77-5c5d-4f7e-b605-a375b3021217)

**Comment by elefantel** [comment]
Hi @dearestwilson. I'm not sure I follow what your screenshot is about, it seems not to have any icon related information as per the issue logged?

**Comment by xionglihui** [comment]
> Hi @xionglihui , are you referring to the icons for the example app? They are not part of the SDK but app icons for the example app.
> 
> They should not be part of the SDK if you add the SDK via `'io.metamask.androidsdk:metamask-android-sdk:0.1.2'` but only when you clone the Github repo. Are you getting it when integrating the SDK this way? In which path is it located?

It is generated by introducing io.metamask.androidsdk:metamask-android-sdk:0.1.2. You can try it.

**Comment by ItMrj** [comment]
![image](https://github.com/MetaMask/metamask-android-sdk/assets/33681925/228c2f56-e5fd-456a-9f93-649df1789c21)
Hi @elefantel ，In the SDK manifest file, this code will cause the user to appear with two desktop application icons
