### ISSUE TITLE
Multiple connection issues

### ISSUE THREAD

**Issue by xionglihui** [MetaMask/metamask-android-sdk#32]
After ethereumViewModel.connect connects to the wallet Address_1 address and then the personal_sign signature jumps to the wallet, click Cancel, then switch the account Address_2 in the wallet, and connect ethereumViewModel.connect to the wallet Address_2 again, but the address returned by ethereumViewModel.selectedAddress is still the last address Address_1. How to solve this?

**Comment by christopherferreira9** [comment]
Hi @xionglihui ! 
I'm so sorry for the late reply!
I just merged a [PR](https://github.com/MetaMask/metamask-mobile/pull/7489) on the mobile side that fixes this.
Thank you for reporting!
