### ISSUE TITLE
Only the first wallet address can be obtained

### ISSUE THREAD

**Issue by 1247576066** [MetaMask/metamask-android-sdk#33]
1、When there are multiple wallet addresses in my metamask, my project applies for authorization from metamask. When metamask is authorized, the current wallet address is displayed, but when I return to my project, I find that the first wallet address is still returned. , this phenomenon also exists in the demo
2. When my project links to the first wallet address of metamask for the first time, and then I want to switch the wallet address of the second metamask, how should I do it? It is invalid in the demo.

**Comment by Killinskillz69** [comment]
https://github.com/MetaMask/metamask-android-sdk/issues/33#issue-1910604429

**Comment by christopherferreira9** [comment]
Hi all! This has been fixed in https://github.com/MetaMask/metamask-mobile/pull/7489
