### ISSUE TITLE
Please make it possible to implement di library as an option

### ISSUE THREAD

**Issue by amuyu** [MetaMask/metamask-android-sdk#42]
It's currently mandatory for the di library to use Dagger-Hilt, 
but it would be great if developers could have the option to implement this part selectively.

For example, some apps might use [Koin](https://insert-koin.io/) instead of Dagger-Hilt with the di library, or they might not use the di library at all. If we restrict it to only use Dagger-Hilt, it might be challenging to use.

It would be a good idea to separate it into a multi-module structure. Like this, 
* base: io.metamask.androidsdk:metamask-android-sdk
* dagger-hilt: io.metamask.androidsdk:di-dagger-hilt
etc,
* viewmodel: io.metamask.androidsdk:lifecycle-viewmodel

**Comment by christopherferreira9** [comment]
Hi @amuyu ! Thank you for your suggestion, we are taking it in consideration.

**Comment by elefantel** [comment]
Hey @amuyu , thanks for reporting this. It was part of our sprint work, we have implemented it. Check latest main branch, you should not need to add hilt dependency anymore. You can opt not to use any dependency manager at all or use any of your choosing.
