### ISSUE TITLE
When I call requestAccounts, only the first address is called.

### ISSUE THREAD

**Issue by amuyu** [MetaMask/metamask-android-sdk#51]
There are two addresses in Metamask.
* Account1 : 0x851408ff3d202fd855d87c73784ed0d58ccc8ed9
* Account2 : 0xb2aDbb9Af253f7C3F7B4b07B248672Fe06E9d691

After selecting Account2 in the Metamask app, when I call requestAccounts, only the address of Account1 is returned, 
so I cannot verify the address of Account2 in the app. It seems like the address of Account2 should be returned, but please verify this.(It seems like the Metamask app returns the address of the initially selected account when connected, rather than returning the currently selected account.)

```
CommunicationClient:: Got message: {"name":"metamask-provider","data":{"id":"e87a0f9a-a821-453e-8c45-e22d3dff8123","result":["0x851408ff3d202fd855d87c73784ed0d58ccc8ed9"]}}
CommunicationClient:: Response for request eth_requestAccounts
CommunicationClient:: Received account changed event: 0x851408ff3d202fd855d87c73784ed0d58ccc8ed9
```

<img src="https://github.com/MetaMask/metamask-android-sdk/assets/4986081/99cc29b0-071a-4c62-b5c1-fb9a964355e8" alt="drawing" width="200"/>
<img src="https://github.com/MetaMask/metamask-android-sdk/assets/4986081/56f965df-b53e-48d1-aa66-fdab51f3ccc4" alt="drawing" width="200"/>
<img src="https://github.com/MetaMask/metamask-android-sdk/assets/4986081/a8ce87a0-ea22-407f-9dcc-1586e99b680f" alt="drawing" width="200"/>

To get 'Account2' through 'requestAccounts,' I need to clear the connected data by going to `Settings > Security & Privacy` and then reconnect". However, when calling 'requestAccounts' on mobile web (Chrome), there is no need to initialize or clear private data; the selected account is retrieved successfully. This behavior should be consistent in the Android SDK as well.

<img src="https://github.com/MetaMask/metamask-android-sdk/assets/4986081/bbd20a07-17f8-4967-b3ed-4a36bf979dc6" alt="drawing" width="200"/>
<img src="https://github.com/MetaMask/metamask-android-sdk/assets/4986081/df5f6532-dcf2-49a5-8b53-107539200165" alt="drawing" width="200"/>

**Comment by christopherferreira9** [comment]
Hi @amuyu !
We have fixed this issue on the [wallet side](https://github.com/MetaMask/metamask-mobile/pull/7489). It should be available in the appstores any time soon.

**Comment by amuyu** [comment]
Thank you!!
