### ISSUE TITLE
[Bug]: Use the demo to connect to the Metamask wallet. After starting Metamask and unlocking Metamask with your fingerprint, no connection pop-up window pops up.

### ISSUE THREAD

**Issue by gxd523** [MetaMask/metamask-android-sdk#59]
### Provide environment information

I cloned the demo code and ran it on my phone. Metamask was installed on my phone. When I clicked to connect, the Metamask application was awakened, and then I used my fingerprint to unlock it. After that, Metamask became unresponsive and the connection pop-up window did not pop up.

### MetaMask Android SDK Version

0.2.1

### MetaMask Mobile app Version

7.12.0

### Android Version

android12

### Describe the Bug

I cloned the demo code and ran it on my phone. Metamask was installed on my phone. When I clicked to connect, the Metamask application was awakened, and then I used my fingerprint to unlock it. After that, Metamask became unresponsive and the connection pop-up window did not pop up.

### Expected Behavior

Metamask should be able to pop up the connection window after I unlock it.

### To Reproduce

![iShot_2023-12-07_17 24 08](https://github.com/MetaMask/metamask-android-sdk/assets/47555132/49eff271-16e4-4cee-95c0-8bc077d98ef0)

**Comment by Cognacy** [comment]
@gxd523 Are you able to resolve this error?

**Comment by christopherferreira9** [comment]
Hi all! We're going to try to replicate this. Can you please share the following details to help us debug: 
- How often it happens
- Specific steps to reproduce this issue

**Comment by gxd523** [comment]
Occurs 100% of the time.
I recorded a video of the operation process:
https://github.com/MetaMask/metamask-android-sdk/assets/47555132/413be397-2a0b-4e83-a58d-dbe46f1c2542
@christopherferreira9

**Comment by christopherferreira9** [comment]
@gxd523 thank you for the video! 
Did the wallet freeze as soon as it opened? Just to be clear, did you manually go to the wallet just before the connection prompt appeared?

**Comment by gxd523** [comment]
@christopherferreira9 The wallet is not frozen or unresponsive, but the connection prompt does not pop up after connecting the wallet to unlock the wallet application for the first time.After that, I switched back to the demo application. At this time, the wallet application is in the task stack. When I click the connection button in the demo again, I can jump to the wallet application normally and the connection prompt pops up. That is to say, when the wallet application has been launched and unlocked, connect the wallet in other applications to pop up the connection prompt normally.

**Comment by christopherferreira9** [comment]
Hi @gxd523 ! We're struggling to reproduce your issue locally. Can you please update the Android SDK version as we released version `0.3.0` a few days ago.

**Comment by andreahaku** [comment]
@Queatz thanks for the log as it's very helpful. We are trying to reproduce it.
Thanks again.

**Comment by christopherferreira9** [comment]
Hi all! We're currently working on stability increases related to the android SDK on the mobile wallet side. Will keep this issue updated once we have that released.

**Comment by christopherferreira9** [comment]
Hi all! `v7.14.0` has been released to the appstores and should be available very soon. Please feel free to open a new issue if you still encounter similar issues with the new version.
