### ISSUE TITLE
[Bug]: android.os.DeadObjectException

### ISSUE THREAD

**Issue by spectrl** [MetaMask/metamask-android-sdk#67]
### Provide environment information

An exception is causing our app, Floor, to crash after integrating the MetaMask SDK on Android.

It has affected around 20% of our users over the last 24-48 hours.

### MetaMask Android SDK Version

0.2.1

### MetaMask Mobile app Version

7.12.2

### Android Version

13

### Describe the Bug

We've just added the MetaMask SDK to our app (Floor), and while it's seems to work fine when testing it on the few devices we have, after publishing the app update we began to see quite a few crashes with our users in the wild... It doesn't seem specific to an Android OS version.

From looking at the log (stacktrace attached) it seems to occur when the `Ethereum.sendRequest` is called, possibly when we try to sign a message, or even during initial connection.

[io.floornfts_issue_d82d2971eeb340860ec17707ce301de0_crash_session_6579DD6201F80001557B9EF0CD0904E0_DNE_1_v2_stacktrace.txt](https://github.com/MetaMask/metamask-android-sdk/files/13665467/io.floornfts_issue_d82d2971eeb340860ec17707ce301de0_crash_session_6579DD6201F80001557B9EF0CD0904E0_DNE_1_v2_stacktrace.txt)

### Expected Behavior

No crashes pls

### To Reproduce

Unable to reproduce :(

**Comment by christopherferreira9** [comment]
Hi @spectrl ! We're going to investigate and try to replicate it. Are you able to share a repo or some code snippets we can check?

**Comment by spectrl** [comment]
Unfortunately I don't have a repo to share, but I can paste in the code we are using to connect and sign via the SDK:
**Connect**
```
override fun connect() {
        val dApp = Dapp("Floor", "https://www.floornfts.io")
        ethereum.connect(dApp) { result ->
            if (result is RequestError) {
                logcat { "Ethereum connection error: ${result.message}" }
            } else {
                logcat { "Ethereum connection result: $result" }
                val address = result as? String
                if (address == null) {
                    logcat { "Unable to retrieve address from result" }
                } else {
                    sign(address)
                }
            }
        }
    }
```
**Sign**
```
override fun sign(message: String, address: String) {
        val params: List<String> = listOf(address, message)
        val signRequest = EthereumRequest(
            id = UUID.randomUUID().toString(),
            method = EthereumMethod.PERSONAL_SIGN.value,
            params = params
        )
        try {
            ethereum.sendRequest(signRequest) { result ->
                if (result is RequestError) {
                    logcat { "Ethereum sign error: ${result.message}" }
                } else {
                    logcat { "Ethereum sign result: $result" }
                    val signature = result as? String
                    if (signature == null) {
                        logcat { "Unable to retrieve signature from result" }
                    } else {
                        logcat { "Signed: $signature" }
                    }
                }
            }
        } catch (e: Exception) {
            logcat { "Ethereum sign error: ${e.message}" }
        }
    }
```

**Comment by christopherferreira9** [comment]
Hi @spectrl ! We will be looking at this further based on the details you provided. Thank you for the bug report!

**Comment by andreahaku** [comment]
Hi @spectrl we are looking into it and working on a fix. Sorry for the slow response but the team has been off until today. Thanks

**Comment by spectrl** [comment]
No worries, thanks for the update!

**Comment by christopherferreira9** [comment]
Hi @spectrl we have been trying to reproduce this issue using a release APK and we couldn't reproduce the same error. We will continue to investigate this issue.

**Comment by spectrl** [comment]
Okay, thanks for the perseverance! I also couldn't reproduce locally but as I mentioned in the original post, after releasing about 20% of our sessions were crashing. If I have some more time at some point, I'll try and create a small repo that mimics our setup but can't promise anything soon 🙃

**Comment by christopherferreira9** [comment]
That would be amazing! Thank you for your prompt feedback!

**Comment by spectrl** [comment]
I really want this to work so that we can stop relying on WalletConnect 🥲

**Comment by christopherferreira9** [comment]
Hi @spectrl ! Did you manage to make some progress on this topic?

**Comment by andreahaku** [comment]
Hi @spectrl we couldn't reproduce the issue and so it's very hard for us to understand where the problem is. Were you able to create the repo that we can use to do it? Thanks a lot

**Comment by andreahaku** [comment]
@spectrl we are closing this as we haven't heard back. Feel free to open the issue again if needed
