### ISSUE TITLE
[Bug]: request account connect pop twice

### ISSUE THREAD

**Issue by philos3** [MetaMask/metamask-android-sdk#94]
### Provide environment information

error

### MetaMask Android SDK Version

io.metamask.androidsdk:metamask-android-sdk:0.5.0

### MetaMask Mobile app Version

no 

### Android Version

android 13

### Describe the Bug

<img width="869" alt="image" src="https://github.com/MetaMask/metamask-android-sdk/assets/8424317/be4aeae6-94d1-4313-9bef-232c527ba7e0">

<img width="1058" alt="image" src="https://github.com/MetaMask/metamask-android-sdk/assets/8424317/aa8e94da-8d42-456b-ab2c-cf58c62ded87">

when i call ethereum.connect  , it shows two identical pop-ups as below window
![image](https://github.com/MetaMask/metamask-android-sdk/assets/8424317/b2adce8e-f38d-409e-8df5-2fd036b1a182)

console log:
MM_ANDROID_SDK(12200): Ethereum:: Sending request EthereumRequest(id=1708423891739, method=eth_requestAccounts, params=null)
D/MM_ANDROID_SDK(12200): CommunicationClient:: sendRequest - not yet connected to metamask, binding service first
D/MM_ANDROID_SDK(12200): CommunicationClient:: Queued job
D/MM_ANDROID_SDK(12200): CommunicationClient:: Binding service
D/MM_ANDROID_SDK(12200): Ethereum:: Sending request EthereumRequest(id=1708423891765, method=eth_chainId, params=null)
D/MM_ANDROID_SDK(12200): CommunicationClient:: sendRequest - not yet connected to metamask, binding service first
D/MM_ANDROID_SDK(12200): CommunicationClient:: Queued job
D/MM_ANDROID_SDK(12200): CommunicationClient:: Binding service
I/flutter (12200): HttpTaskManager进入AppLifecycleState.inactive
D/MM_ANDROID_SDK(12200): CommunicationClient:: Service connected ComponentInfo{io.metamask/io.metamask.nativesdk.MessageService}
D/MM_ANDROID_SDK(12200): CommunicationClient:: Initiating key exchange

### Expected Behavior

pop window one time

### To Reproduce

ethereum.connect

**Comment by elefantel** [comment]
Hi @philos3 thanks for the issue! The issue of the connect prompt showing up twice has been fixed in the metamask wallet version 7.16. It's already on the AppStore but still at 2% rollout as of writing of this message.

**Comment by philos3** [comment]
what is the fix version of metamask-android-sdk

**Comment by elefantel** [comment]
@philos3 there were no changes required pertaining to this issue from the android sdk side.
