### ISSUE TITLE
[Bug]: Demo crashes when clicking connect

### ISSUE THREAD

**Issue by Leney** [MetaMask/metamask-android-sdk#98]
### Provide environment information

After I run the demo and click Connect and other buttons, a crash occurs.
When introduced as a Mave repository in my app, the same crash occurs using api connect.
Can I only introduce it into my project as source code and then remove this judgment?
![WX20240229-001205@2x](https://github.com/MetaMask/metamask-android-sdk/assets/9280041/fbe6d5bf-2024-4bbf-82f1-93b46a07e8c3)

### MetaMask Android SDK Version

0.5.0

### MetaMask Mobile app Version

v7.16.0

### Android Version

Android 7.1.1 and Android 12

### Describe the Bug

After I run the demo and click Connect and other buttons, a crash occurs.
When introduced as a Mave repository in my app, the same crash occurs using api connect.

### Expected Behavior

After I run the demo and click Connect and other buttons, a crash occurs.
When introduced as a Mave repository in my app, the same crash occurs using api connect.

### To Reproduce

The code location where the exception occurred：io.metamask.androidsdk.CommunicationClient
![2](https://github.com/MetaMask/metamask-android-sdk/assets/9280041/ce657323-12bf-4398-b9d4-6d78e51051f7)

@RequiresApi(Build.VERSION_CODES.TIRAMISU)
    private fun isQA(): Boolean {
        val packageManager = appContextRef.get()?.packageManager

        return try {
            packageManager?.getPackageInfo("io.metamask.qa", PackageManager.PackageInfoFlags.of(0))
            true
        } catch (e: PackageManager.NameNotFoundException) {
            false
        }
    }

**Comment by elefantel** [comment]
Hi @Leney The SDK has targetSdk 33. I see you are on Android 12. We have mad a change to fix the crash in this [MR](https://github.com/MetaMask/metamask-android-sdk/pull/99/files). So the demo app should work fine now. We have not released a new version with this change though for now.

**Comment by christopherferreira9** [comment]
Closing this issue for now. Please feel free to open a new issue if you encounter any other issues.

**Comment by philos3** [comment]
any release version update ? it is still 0.5.0

**Comment by elefantel** [comment]
@philos3 0.5.1 fixes the issue, thanks!
